// PhD-grade deep-research engine, running fully locally on Gemma.
//
// Pipeline (strict input boundaries — agents cannot influence each other):
//   1. ORCHESTRATOR  restates the question and decomposes it into 3–7
//                    sub-questions. It performs no research itself.
//   2. RESEARCHERS   one ISOLATED pass per sub-question: each sees only its
//                    sub-question (+ real OrioSearch results when enabled) —
//                    never the other agents' work. Facts + citations + gaps.
//   3. ANALYST       sees only the Researchers' notes. Synthesizes insights,
//                    models/frameworks, implications, uncertainties.
//   4. CRITIC        sees Researcher + Analyst outputs plus the machine-built
//                    list of VERIFIED sources. Adversarial review + verdict.
//   5. REVISION      if the Critic's verdict is MAJOR_ISSUES, the Orchestrator
//                    relays the required corrections to the Analyst (bounded
//                    cycles), then the Critic re-reviews.
//   6. ORCHESTRATOR  integrates everything into the final structured report.
//
// Anti-hallucination protocol:
//   • Every agent is instructed: no invented facts/URLs; mark UNKNOWN /
//     UNVERIFIED explicitly; reason internally but output only conclusions.
//   • MECHANICAL citation verification: the app records every URL OrioSearch
//     actually returned (the "evidence ledger"). Cited URLs are checked
//     against it in code — an LLM never "verifies" anything on trust.
//   • The final References section is assembled by code from the ledger
//     (only real, cited sources), never generated by the model.

import { formatSearchForPrompt, type SearchResult } from './search';

export type SubAgentId = 'researcher' | 'analyst' | 'critic' | 'verifier';

export interface AgentMeta {
  id: SubAgentId | 'orchestrator';
  name: string;
  accent: string; // tailwind text color class
  dot: string; // hex for the gutter dot
}

export const AGENT_META: Record<SubAgentId | 'orchestrator', AgentMeta> = {
  orchestrator: { id: 'orchestrator', name: 'Orchestrator', accent: 'text-[var(--color-neon)]', dot: '#ff3da6' },
  researcher: { id: 'researcher', name: 'Researcher', accent: 'text-sky-300', dot: '#38bdf8' },
  analyst: { id: 'analyst', name: 'Analyst', accent: 'text-violet-300', dot: '#a78bfa' },
  critic: { id: 'critic', name: 'Critic', accent: 'text-rose-300', dot: '#fb7185' },
  verifier: { id: 'verifier', name: 'Verifier', accent: 'text-teal-300', dot: '#2dd4bf' },
};

export interface Todo {
  id: string;
  title: string;
  agent: SubAgentId;
  status: 'pending' | 'running' | 'done';
  fileOut?: string;
  round: number;
}

export interface VfsFile {
  name: string;
  summary: string;
  content: string;
}

export type CriticVerdict = 'SOUND' | 'MINOR_ISSUES' | 'MAJOR_ISSUES';

// ---- Shared prompt fragments ----------------------------------------------

const NO_COT = `Reason through the task internally, but output ONLY your conclusions in the exact format below — no chain-of-thought, no preamble, nothing before the first marker.`;

const ANTI_HALLUCINATION = `
Anti-hallucination protocol (mandatory):
- Do NOT invent facts, statistics, names, quotes, or URLs.
- Only cite URLs that literally appear in the sources provided to you.
- If something is unknown, not covered by the sources, or uncertain, write UNKNOWN or UNVERIFIED explicitly — never guess.`;

// ---- Agent prompts (PhD-level, hallucination-resistant) --------------------

const ORCH_PLAN_PROMPT = `You are the ORCHESTRATOR agent — a senior research director overseeing a team of PhD-level specialists (Researcher, Analyst, Critic). You do NOT perform research yourself. You think independently and adopt no one's assumptions.
${ANTI_HALLUCINATION}
${NO_COT}

Reply in EXACTLY this format:
@@QUESTION@@
(the main research question, restated precisely in one sentence)
@@SUBQUESTIONS@@
1. (first precise sub-question)
2. (second precise sub-question)
3. (third precise sub-question)
(3–7 sub-questions total; each must be answerable independently and together they must cover the main question)`;

const RESEARCHER_PROMPT = `You are the RESEARCHER agent — a PhD-level academic performing a deep literature search for ONE assigned sub-question. You work in ISOLATION: you know nothing about other agents and must not speculate about them.

Rules:
- Report ONLY verifiable facts: data, statistics, definitions, named techniques, expert findings.
- Do NOT analyze, critique, speculate, or draw conclusions — that is not your role.
- Every factual claim must carry a citation URL taken from the provided web sources. If no sources are provided, cite nothing and mark claims UNVERIFIED.
- List what you could NOT find as gaps.
${ANTI_HALLUCINATION}
${NO_COT}

Reply in EXACTLY this format:
@@SUMMARY@@
(1–2 sentence summary of what you found)
@@NOTES@@
## Findings
- (fact) [URL]
- (fact) [URL]
## Citations
- URL — what it supports
## Gaps
- (missing data / unanswered aspects, marked UNKNOWN or UNVERIFIED)`;

const ANALYST_PROMPT = `You are the ANALYST agent — a PhD-level academic synthesizer. You see ONLY the Researchers' notes below. You must not perform new research or adversarial critique.

Rules:
- Rely STRICTLY on the Researchers' findings and citations; do not add facts they did not report.
- Identify patterns, causal relationships, and theoretical implications.
- Build models or frameworks in text/markdown form (tables, layered diagrams, step flows).
- State remaining uncertainties honestly.
${ANTI_HALLUCINATION}
${NO_COT}

Reply in EXACTLY this format:
@@SUMMARY@@
(1–2 sentence summary of your synthesis)
@@NOTES@@
## Key insights
## Theoretical analysis
## Models / frameworks
## Implications
## Remaining uncertainties`;

const CRITIC_PROMPT = `You are the CRITIC agent — an adversarial peer reviewer for a top-tier academic journal. You see the Researchers' notes, the Analyst's synthesis, and the machine-verified source list.

Rules:
- The "VERIFIED SOURCES" list below is ground truth: any cited URL NOT on it is unverified — flag it. Do not claim to have checked sources yourself beyond this list.
- Identify unsupported claims, logical fallacies, weak assumptions, and methodological gaps.
- Propose concrete corrections. Do NOT produce new research or new analysis.
- End with a verdict: SOUND, MINOR_ISSUES, or MAJOR_ISSUES.
${ANTI_HALLUCINATION}
${NO_COT}

Reply in EXACTLY this format:
@@VERDICT@@
(SOUND or MINOR_ISSUES or MAJOR_ISSUES)
@@SUMMARY@@
(1–2 sentence overall judgement)
@@NOTES@@
## Citation check
## Unsupported claims
## Logical inconsistencies
## Methodological weaknesses
## Required corrections`;

const VERIFIER_PROMPT = `You are the VERIFIER agent — a fact-checking specialist. You receive factual claims and REAL excerpts machine-fetched from the cited web pages. Judge each claim STRICTLY against the excerpts.

Rules:
- Judge ONLY from the provided excerpts — never from your own knowledge.
- SUPPORTED: an excerpt directly states or clearly implies the claim.
- PARTIAL: an excerpt is related but does not fully support the claim.
- NOT_FOUND: nothing in the excerpts supports the claim.
- Do not rewrite, correct, or improve the claims. Do not add commentary beyond the verdict lines.
${ANTI_HALLUCINATION}
${NO_COT}

Reply in EXACTLY this format:
@@SUMMARY@@
(one sentence: N supported, N partial, N not found)
@@NOTES@@
## Claim verification
1. (claim, shortened) — SUPPORTED | PARTIAL | NOT_FOUND
2. ...`;

const ORCH_FINAL_PROMPT = `You are the ORCHESTRATOR integrating your team's completed work into a final rigorous research report. Reject any claim that lacks evidence: if the Critic flagged something as unsupported and it was not corrected, either omit it or explicitly mark it UNVERIFIED.

Rules:
- Add NO new facts of your own.
- Do NOT write a references/bibliography section — it is appended automatically from verified sources.
${ANTI_HALLUCINATION}
${NO_COT}

Reply with a Markdown report in EXACTLY this structure:
## Executive summary
## Sub-questions
## Evidence summary
## Analytical synthesis
## Critical review summary
## Final integrated conclusion
## Remaining uncertainties`;

// ---- Parsing helpers --------------------------------------------------------

function section(raw: string, marker: string, nexts: string[]): string {
  const i = raw.indexOf(marker);
  if (i < 0) return '';
  const start = i + marker.length;
  let end = raw.length;
  for (const m of nexts) {
    const j = raw.indexOf(m, start);
    if (j >= 0 && j < end) end = j;
  }
  return raw.slice(start, end).trim();
}

function parseNumbered(text: string): string[] {
  const out: string[] = [];
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*\d+[.)]\s*(.+?)\s*$/);
    if (m && m[1] && !/^\(/.test(m[1])) out.push(m[1].replace(/\*\*/g, '').slice(0, 200));
  }
  return out;
}

function parseSummaryNotes(raw: string): { summary: string; notes: string } {
  const summary = section(raw, '@@SUMMARY@@', ['@@NOTES@@']);
  const notes = section(raw, '@@NOTES@@', []);
  if (!summary && !notes) {
    const trimmed = raw.trim();
    return { summary: trimmed.split('\n')[0]?.slice(0, 160) || '', notes: trimmed };
  }
  return { summary, notes: notes || raw.trim() };
}

function parseVerdict(raw: string): CriticVerdict {
  const v = section(raw, '@@VERDICT@@', ['@@SUMMARY@@', '@@NOTES@@']) || raw.slice(0, 200);
  if (/major/i.test(v)) return 'MAJOR_ISSUES';
  if (/minor/i.test(v)) return 'MINOR_ISSUES';
  return 'SOUND';
}

// Extract cited URLs from agent text (for mechanical verification).
function extractUrls(text: string): string[] {
  const found = text.match(/https?:\/\/[^\s)\]"'<>]+/g) ?? [];
  return [...new Set(found.map((u) => u.replace(/[.,;:!?]+$/, '')))];
}

function normalizeUrl(u: string): string {
  return u.replace(/\/+$/, '').toLowerCase();
}

// Pull the factual claims (Findings bullets) out of a researcher's notes so the
// Verifier can check them against real page content.
function extractClaims(notes: string): string[] {
  const lines = notes.split('\n');
  const claims: string[] = [];
  let inFindings = false;
  for (const l of lines) {
    if (/^##\s*Findings/i.test(l)) {
      inFindings = true;
      continue;
    }
    if (/^##\s/.test(l) && inFindings) break;
    if (inFindings) {
      const m = l.match(/^\s*[-*]\s*(.+)$/);
      if (m) {
        const claim = m[1]
          .replace(/\[[^\]]*\]|\(https?:\/\/[^)]*\)|https?:\/\/\S+/g, '')
          .replace(/\*\*/g, '')
          .trim();
        if (claim.length > 12) claims.push(claim.slice(0, 200));
      }
    }
  }
  // Fallback: any bullet lines if the model skipped the Findings heading.
  if (!claims.length) {
    for (const l of lines) {
      const m = l.match(/^\s*[-*]\s*(.+)$/);
      if (m && m[1].length > 12) claims.push(m[1].slice(0, 200));
    }
  }
  return claims.slice(0, 8);
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 32) || 'note';
}

// ---- Events -----------------------------------------------------------------

export type DeepEvent =
  | { type: 'plan:start' }
  | { type: 'plan:token'; raw: string }
  | { type: 'plan:done'; question: string; todos: Todo[] }
  | { type: 'todos'; todos: Todo[] }
  | { type: 'task:start'; todo: Todo }
  | { type: 'task:token'; todoId: string; raw: string }
  | { type: 'task:done'; todoId: string; summary: string; file: string }
  | { type: 'citations'; todoId: string; verified: number; unverified: number; unverifiedUrls: string[] }
  | { type: 'entailment'; todoId: string; supported: number; partial: number; notFound: number }
  | { type: 'verdict'; verdict: CriticVerdict; cycle: number }
  | { type: 'search:start'; todoId: string }
  | { type: 'search:done'; todoId: string; count: number }
  | { type: 'search:error'; todoId: string; message: string }
  | { type: 'fs'; files: VfsFile[] }
  | { type: 'review:done'; round: number; decision: string; reason: string }
  | { type: 'final:start' }
  | { type: 'final:token'; raw: string }
  | { type: 'final:done'; report: string }
  | { type: 'done'; reason: string };

export interface DeepOptions {
  topic: string;
  // Bounded critic→analyst correction cycles after the first review (0–2).
  maxRevisions: number;
  generate: (prompt: string, systemPrompt?: string) => AsyncGenerator<string>;
  isCancelled: () => boolean;
  onEvent: (e: DeepEvent) => void;
  webSearch?: (query: string) => Promise<SearchResult[]>;
  // Content-entailment upgrade: fetch REAL page text for cited URLs (OrioSearch
  // /extract) so the Verifier can judge claims against actual sources.
  webExtract?: (urls: string[]) => Promise<{ url: string; content: string }[]>;
}

// ---- Engine -------------------------------------------------------------------

export async function runDeepResearch(opts: DeepOptions): Promise<void> {
  const { topic, maxRevisions, generate, isCancelled, onEvent, webSearch, webExtract } = opts;

  const vfs: VfsFile[] = [];
  const todos: Todo[] = [];
  let fileCounter = 0;

  // Evidence ledger: every URL OrioSearch actually returned (ground truth for
  // mechanical citation verification), plus which of them agents cited.
  const ledger = new Map<string, string>(); // normalized url -> title
  const citedVerified = new Map<string, string>(); // url -> title (cited AND real)

  const emitTodos = () => onEvent({ type: 'todos', todos: todos.map((t) => ({ ...t })) });
  const emitFs = () => onEvent({ type: 'fs', files: vfs.map((f) => ({ ...f })) });

  async function stream(
    system: string,
    prompt: string,
    onTok: (raw: string) => void,
  ): Promise<string> {
    let raw = '';
    for await (const tok of generate(prompt, system)) {
      if (isCancelled()) break;
      raw += tok;
      onTok(raw);
    }
    return raw;
  }

  // Mechanical citation check: which cited URLs are real (in the ledger)?
  function verifyCitations(text: string): { verified: string[]; unverified: string[] } {
    const verified: string[] = [];
    const unverified: string[] = [];
    for (const url of extractUrls(text)) {
      const n = normalizeUrl(url);
      let hit: string | undefined;
      for (const [known, title] of ledger) {
        if (known === n || known.startsWith(n) || n.startsWith(known)) {
          hit = title;
          break;
        }
      }
      if (hit !== undefined) {
        verified.push(url);
        citedVerified.set(url, hit);
      } else {
        unverified.push(url);
      }
    }
    return { verified, unverified };
  }

  function addFile(agent: SubAgentId, title: string, summary: string, content: string): string {
    const name = `${++fileCounter}-${agent}-${slug(title)}.md`;
    vfs.push({ name, summary: summary || content.slice(0, 140), content });
    emitFs();
    return name;
  }

  // Run one sub-agent task: stream → parse → store → (researcher) verify cites.
  async function runTask(
    todo: Todo,
    system: string,
    prompt: string,
  ): Promise<{ summary: string; notes: string; raw: string }> {
    todo.status = 'running';
    emitTodos();
    onEvent({ type: 'task:start', todo: { ...todo } });
    const raw = await stream(system, prompt, (r) =>
      onEvent({ type: 'task:token', todoId: todo.id, raw: r }),
    );
    const { summary, notes } = parseSummaryNotes(raw);
    const file = addFile(todo.agent, todo.title, summary, notes);
    todo.status = 'done';
    todo.fileOut = file;
    onEvent({ type: 'task:done', todoId: todo.id, summary, file });
    if (todo.agent === 'researcher') {
      const { verified, unverified } = verifyCitations(notes);
      onEvent({
        type: 'citations',
        todoId: todo.id,
        verified: verified.length,
        unverified: unverified.length,
        unverifiedUrls: unverified,
      });
    }
    emitTodos();
    return { summary, notes, raw };
  }

  // ---- 1) ORCHESTRATOR: decompose the question ---------------------------
  onEvent({ type: 'plan:start' });
  const planRaw = await stream(
    ORCH_PLAN_PROMPT,
    `Main research question: ${topic}\n\nDecompose it.`,
    (raw) => onEvent({ type: 'plan:token', raw }),
  );
  const question = section(planRaw, '@@QUESTION@@', ['@@SUBQUESTIONS@@']) || topic;
  let subQuestions = parseNumbered(section(planRaw, '@@SUBQUESTIONS@@', [])).slice(0, 7);
  if (subQuestions.length < 3) {
    // Fallback decomposition so a malformed reply never stalls the run.
    subQuestions = [
      `What is the current state of knowledge and practice on: ${topic}?`,
      `What evidence, data, and concrete approaches exist for: ${topic}?`,
      `What are the main limitations, risks, and open problems in: ${topic}?`,
    ];
  }
  for (const sq of subQuestions) {
    todos.push({ id: crypto.randomUUID(), title: sq, agent: 'researcher', status: 'pending', round: 1 });
  }
  onEvent({ type: 'plan:done', question, todos: todos.map((t) => ({ ...t })) });

  // ---- 2) RESEARCHERS: isolated pass per sub-question ---------------------
  const researchNotes: { title: string; summary: string; notes: string }[] = [];
  const claimChecks: string[] = []; // Verifier results, fed to the Critic
  for (const todo of todos.filter((t) => t.agent === 'researcher')) {
    if (isCancelled()) break;

    let webBlock = '';
    if (webSearch) {
      onEvent({ type: 'search:start', todoId: todo.id });
      try {
        const res = await webSearch(`${topic} ${todo.title}`.slice(0, 300));
        for (const r of res) ledger.set(normalizeUrl(r.url), r.title);
        webBlock = formatSearchForPrompt(res.slice(0, 6), todo.title);
        onEvent({ type: 'search:done', todoId: todo.id, count: res.length });
      } catch (err) {
        onEvent({ type: 'search:error', todoId: todo.id, message: (err as Error).message });
      }
    }

    const prompt =
      `Sub-question assigned to you (work in isolation): ${todo.title}\n\n` +
      (webBlock
        ? `${webBlock}\n\nUse ONLY these sources for citations.`
        : `No web sources are available for this run. Rely on well-established knowledge only, cite NO URLs, and mark anything uncertain as UNVERIFIED.`);

    const { summary, notes } = await runTask(todo, RESEARCHER_PROMPT, prompt);
    researchNotes.push({ title: todo.title, summary, notes });

    // ---- 2b) VERIFIER: content entailment against REAL page text ---------
    // The app fetches the cited pages (code, not LLM); the Verifier judges
    // each claim strictly against the fetched excerpts.
    if (webExtract && !isCancelled()) {
      const { verified } = verifyCitations(notes);
      const claims = extractClaims(notes);
      if (verified.length && claims.length) {
        let excerpts: { url: string; content: string }[] = [];
        try {
          excerpts = await webExtract(verified.slice(0, 3));
        } catch {
          /* extraction unavailable — skip verification for this note */
        }
        if (excerpts.length) {
          const vTodo: Todo = {
            id: crypto.randomUUID(),
            title: `Verify claims — ${todo.title.slice(0, 90)}`,
            agent: 'verifier',
            status: 'pending',
            round: 1,
          };
          todos.push(vTodo);
          emitTodos();
          const exBlock = excerpts
            .map((e) => `SOURCE: ${e.url}\n${e.content.slice(0, 1100)}`)
            .join('\n\n---\n\n');
          const vRes = await runTask(
            vTodo,
            VERIFIER_PROMPT,
            `Claims to verify:\n${claims.map((c, i) => `${i + 1}. ${c}`).join('\n')}\n\n` +
              `REAL page excerpts (machine-fetched from the cited URLs):\n${exBlock}\n\nVerify each claim now.`,
          );
          const s = (vRes.notes.match(/\bSUPPORTED\b/g) || []).length;
          const p = (vRes.notes.match(/\bPARTIAL\b/g) || []).length;
          const nf = (vRes.notes.match(/\bNOT_FOUND\b/g) || []).length;
          onEvent({ type: 'entailment', todoId: vTodo.id, supported: s, partial: p, notFound: nf });
          claimChecks.push(
            `Sub-question "${todo.title.slice(0, 90)}": ${s} supported, ${p} partial, ${nf} not found in fetched sources.\n${vRes.notes.slice(0, 450)}`,
          );
        }
      }
    }
  }

  // ---- 3) ANALYST: synthesis (sees only Researcher notes) -----------------
  let analystNotes = '';
  if (!isCancelled()) {
    const todo: Todo = {
      id: crypto.randomUUID(),
      title: 'Synthesize findings into insights, models, and implications',
      agent: 'analyst',
      status: 'pending',
      round: 2,
    };
    todos.push(todo);
    emitTodos();
    const body = researchNotes
      .map((n) => `### Sub-question: ${n.title}\n${n.notes.slice(0, 1400)}`)
      .join('\n\n');
    const res = await runTask(
      todo,
      ANALYST_PROMPT,
      `Main question: ${question}\n\nResearchers' notes:\n\n${body}\n\nSynthesize now.`,
    );
    analystNotes = res.notes;
  }

  // ---- 4) CRITIC (+ bounded revision cycles) -------------------------------
  let criticNotes = '';
  let verdict: CriticVerdict = 'SOUND';
  const verifiedList = [...citedVerified.entries()]
    .map(([url, title]) => `- ${title} — ${url}`)
    .join('\n');

  let cycle = 0;
  while (!isCancelled()) {
    cycle += 1;
    const critTodo: Todo = {
      id: crypto.randomUUID(),
      title: cycle === 1 ? 'Adversarial review of research + synthesis' : `Re-review after revision ${cycle - 1}`,
      agent: 'critic',
      status: 'pending',
      round: 2 + cycle,
    };
    todos.push(critTodo);
    emitTodos();

    const researchBody = researchNotes
      .map((n) => `### ${n.title}\n${n.notes.slice(0, 900)}`)
      .join('\n\n');
    const critRes = await runTask(
      critTodo,
      CRITIC_PROMPT,
      `Main question: ${question}\n\n` +
        `VERIFIED SOURCES (machine-checked — any other cited URL is unverified):\n${verifiedList || '(none — this run had no web sources; treat all URLs as unverified)'}\n\n` +
        `CLAIM VERIFICATION (claims judged against machine-fetched page content):\n${claimChecks.join('\n\n').slice(0, 1100) || '(no deep verification this run)'}\n\n` +
        `Researchers' notes:\n${researchBody}\n\n` +
        `Analyst's synthesis:\n${analystNotes.slice(0, 1600)}\n\nReview now.`,
    );
    criticNotes = critRes.notes;
    verdict = parseVerdict(critRes.raw);
    onEvent({ type: 'verdict', verdict, cycle });

    // Orchestrator decision: revise or accept.
    if (verdict === 'MAJOR_ISSUES' && cycle <= maxRevisions) {
      onEvent({
        type: 'review:done',
        round: cycle,
        decision: 'REVISE',
        reason: 'Critic found major issues — Orchestrator requires the Analyst to correct them.',
      });
      const revTodo: Todo = {
        id: crypto.randomUUID(),
        title: `Revise synthesis to address the Critic's required corrections (cycle ${cycle})`,
        agent: 'analyst',
        status: 'pending',
        round: 2 + cycle,
      };
      todos.push(revTodo);
      emitTodos();
      const researchBodyShort = researchNotes
        .map((n) => `### ${n.title}\n${n.notes.slice(0, 900)}`)
        .join('\n\n');
      // The Orchestrator mediates: the Analyst receives corrections as
      // director's instructions, preserving the no-direct-influence boundary.
      const revRes = await runTask(
        revTodo,
        ANALYST_PROMPT,
        `Main question: ${question}\n\nResearchers' notes:\n${researchBodyShort}\n\n` +
          `The research director requires a revised synthesis addressing these review findings (fix unsupported claims, remove or mark UNVERIFIED content):\n${criticNotes.slice(0, 1200)}\n\nProduce the corrected synthesis.`,
      );
      analystNotes = revRes.notes;
      continue; // critic re-reviews the revision
    }

    onEvent({
      type: 'review:done',
      round: cycle,
      decision: 'ACCEPT',
      reason:
        verdict === 'SOUND'
          ? 'Critic judged the work sound.'
          : verdict === 'MINOR_ISSUES'
            ? 'Minor issues noted — carried into the final report as caveats.'
            : 'Major issues remain but the revision budget is exhausted — flagged in the final report.',
    });
    break;
  }

  // ---- 5) ORCHESTRATOR: final integrated report ----------------------------
  if (!isCancelled()) {
    onEvent({ type: 'final:start' });
    const researchSummaries = researchNotes
      .map((n, i) => `${i + 1}. ${n.title}\n   ${n.summary || n.notes.slice(0, 160)}`)
      .join('\n');
    const finalRaw = await stream(
      ORCH_FINAL_PROMPT,
      `Main question: ${question}\n\nSub-questions and researcher summaries:\n${researchSummaries}\n\n` +
        `Analyst synthesis:\n${analystNotes.slice(0, 1800)}\n\n` +
        `Critic review (verdict: ${verdict}):\n${criticNotes.slice(0, 1200)}\n\nIntegrate the final report now.`,
      (raw) => onEvent({ type: 'final:token', raw }),
    );

    // References are assembled by CODE from the evidence ledger — only sources
    // that (a) really came from OrioSearch and (b) were actually cited.
    let report = finalRaw.trim();
    if (citedVerified.size) {
      const refs = [...citedVerified.entries()]
        .map(([url, title], i) => `${i + 1}. ${title} — ${url}`)
        .join('\n');
      report += `\n\n## References (machine-verified sources)\n${refs}`;
    } else {
      report += `\n\n## References\n_No machine-verified web sources were cited in this run${webSearch ? '' : ' (web research was off)'}. Treat factual claims as UNVERIFIED model knowledge._`;
    }
    onEvent({ type: 'final:done', report });
  }

  onEvent({ type: 'done', reason: isCancelled() ? 'Stopped.' : `Research complete — verdict: ${verdict}.` });
}
